@ECHO OFF
ECHO "---Setting up the environment"
SET VERCEL_ORG_ID=0UfjtJDO1zoi0cTIdTgjOFmd
SET VERCEL_PROJECT_ID=QmPHaik26ebEMrHvm37wPD9RTKQSqxhH9thtXw71UP6KGh
SET VERCEL_TOKEN=5nRQpWoeqRyIATa7QreqsI79cd